# Generated by Django 4.1.4 on 2022-12-27 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, verbose_name='Business Category Name')),
                ('business_status', models.SmallIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=1, verbose_name='Business Status')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, verbose_name='Category Name')),
                ('category_status', models.SmallIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=1, verbose_name='Category Status')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=255, verbose_name='Country Name')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=255, verbose_name='Category Name')),
                ('subcategory_status', models.SmallIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=1, verbose_name='Category Status')),
                ('category_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('discount', models.PositiveIntegerField(help_text='Max Discount 100%', verbose_name='Discount Percentages')),
                ('description', models.TextField()),
                ('deal_sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_subcat', to='core.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=255, verbose_name='City Name')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='core.country')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255, verbose_name='Business Name')),
                ('address', models.TextField(verbose_name='Business Address')),
                ('license_no', models.CharField(max_length=255, verbose_name='License Number')),
                ('picture', models.FileField(blank=True, null=True, upload_to='business/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_city', to='core.businesscategory')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_city', to='core.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_country', to='core.country')),
            ],
        ),
    ]
